services:
  django:
    build: 
      context: .
      dockerfile: docker/Dockerfile.django
    env_file: .env
    ports:
      - "8000:8000"

  nginx:
    build: 
      context: .
      dockerfile: docker/Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django

  