# Generated by Django 5.1.2 on 2024-11-03 21:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconchar', models.CharField(max_length=8)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #AABBCC).', regex='^#([A-Fa-f0-9]{6})$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
