# Generated by Django 5.1.2 on 2024-11-10 01:32

import django.core.validators
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_housemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemember',
            name='color_hex',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #AABBCC).', regex='^#([A-Fa-f0-9]{6})$')]),
        ),
        migrations.AlterField(
            model_name='taskcompletionrecord',
            name='timestamp',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
    ]
