# Usa una imagen base de Python
FROM python:3.11-bullseye

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8000


# Start the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
